// Generated from the ordered A-line dispatcher declarations.
// Do not edit by hand.
[
    DefaultTrapRoute::new(0xA000, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA001, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA002, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA003, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA004, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA005, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA006, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA007, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA008, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA009, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA00A, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA00B, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA00C, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA00D, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA00E, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA00F, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA010, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA011, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA012, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA013, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA014, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA015, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA016, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA017, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA018, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA019, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA01A, TrapAdapterId::Memory.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA01B, TrapAdapterId::Memory.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA01C, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA01D, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA01E, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA01F, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA020, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA021, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA022, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA023, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA024, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA025, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA026, TrapAdapterId::Memory.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA027, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA028, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA029, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA02A, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA02B, TrapAdapterId::Memory.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA02C, TrapAdapterId::Memory.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA02D, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA02E, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA02F, TrapAdapterId::Event.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA030, TrapAdapterId::Event.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA031, TrapAdapterId::Event.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA032, TrapAdapterId::Event.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA033, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA034, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA035, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA036, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA037, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA038, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA039, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA03A, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA03B, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA03C, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA03D, TrapAdapterId::Event.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA03E, TrapAdapterId::Event.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA03F, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA040, TrapAdapterId::Memory.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA041, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA042, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA043, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA044, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA045, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA046, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA047, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA048, TrapAdapterId::Memory.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA049, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA04A, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA04B, TrapAdapterId::Memory.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA04C, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA04D, TrapAdapterId::Memory.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA04E, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA04F, TrapAdapterId::Event.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA050, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA051, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA052, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA053, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA054, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA055, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA056, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA057, TrapAdapterId::Memory.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA058, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA059, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA05A, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA05B, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA05C, TrapAdapterId::Memory.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA05D, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA05E, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA05F, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA060, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA061, TrapAdapterId::Memory.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA062, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA063, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA064, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA065, TrapAdapterId::Memory.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA066, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA067, TrapAdapterId::Memory.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA068, TrapAdapterId::Memory.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA069, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA06A, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA06B, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA06C, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA06D, TrapAdapterId::Event.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA06E, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA06F, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA070, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA071, TrapAdapterId::Event.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA072, TrapAdapterId::Event.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA073, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA074, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA075, TrapAdapterId::Event.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA076, TrapAdapterId::Event.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA077, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA078, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA079, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA07A, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA07B, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA07C, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA07D, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA07E, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA07F, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA080, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA081, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA082, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA083, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA084, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA085, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA086, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA087, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA088, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA089, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA08A, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA08B, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA08C, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA08D, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA08E, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA08F, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA090, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA091, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA092, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA093, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA094, TrapAdapterId::Resource.mask()),
    DefaultTrapRoute::new(0xA095, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA096, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA097, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA098, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA099, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA09A, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA09B, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA09C, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA09D, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA09E, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA09F, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA0A0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0A1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0A2, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0A3, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0A4, TrapAdapterId::Memory.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0A5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0A6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0A7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0A8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0A9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0AA, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0AB, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0AC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0AD, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0AE, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA0AF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0B0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0B1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0B2, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0B3, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0B4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0B5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0B6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0B7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0B8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0B9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0BA, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0BB, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0BC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0BD, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA0BE, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0BF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0C0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0C1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0C2, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0C3, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0C4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0C5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0C6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0C7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0C8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0C9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0CA, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0CB, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0CC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0CD, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0CE, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0CF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0D0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0D1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0D2, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0D3, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0D4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0D5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0D6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0D7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0D8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0D9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0DA, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0DB, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0DC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0DD, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA0DE, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0DF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0E0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0E1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0E2, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0E3, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0E4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0E5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0E6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0E7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0E8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0E9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0EA, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0EB, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0EC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0ED, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0EE, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0EF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0F0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0F1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0F2, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0F3, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0F4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0F5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0F6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0F7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0F8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0F9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0FA, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0FB, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0FC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0FD, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0FE, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA0FF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA800, TrapAdapterId::Sound.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA801, TrapAdapterId::Sound.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA802, TrapAdapterId::Sound.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA803, TrapAdapterId::Sound.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA804, TrapAdapterId::Sound.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA805, TrapAdapterId::Sound.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA806, TrapAdapterId::Sound.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA807, TrapAdapterId::Sound.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA808, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA809, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA80A, TrapAdapterId::Window.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA80B, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA80C, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA80D, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA80E, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA80F, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA810, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA811, TrapAdapterId::Dialog.mask()),
    DefaultTrapRoute::new(0xA812, TrapAdapterId::Dialog.mask()),
    DefaultTrapRoute::new(0xA813, TrapAdapterId::Dialog.mask()),
    DefaultTrapRoute::new(0xA814, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA815, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA816, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA817, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA818, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA819, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA81A, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA81B, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA81C, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA81D, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA81E, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA81F, TrapAdapterId::Resource.mask()),
    DefaultTrapRoute::new(0xA820, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA821, TrapAdapterId::Resource.mask()),
    DefaultTrapRoute::new(0xA822, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA823, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA824, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA825, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA826, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA827, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA828, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA829, TrapAdapterId::Window.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA82A, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA82B, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA82C, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA82D, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA82E, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA82F, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA830, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA831, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA832, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA833, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA834, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA835, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA836, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA837, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA838, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA839, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA83A, TrapAdapterId::Window.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA83B, TrapAdapterId::Window.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA83C, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA83D, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA83E, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA83F, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA840, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA841, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA842, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA843, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA844, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA845, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA846, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA847, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA848, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA849, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA84A, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA84B, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA84C, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA84D, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA84E, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA84F, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA850, TrapAdapterId::Dialog.mask()),
    DefaultTrapRoute::new(0xA851, TrapAdapterId::Dialog.mask()),
    DefaultTrapRoute::new(0xA852, TrapAdapterId::Dialog.mask()),
    DefaultTrapRoute::new(0xA853, TrapAdapterId::Dialog.mask()),
    DefaultTrapRoute::new(0xA854, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA855, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA856, TrapAdapterId::Dialog.mask()),
    DefaultTrapRoute::new(0xA857, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA858, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA859, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA85A, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA85B, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA85C, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA85D, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA85E, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA85F, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA860, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA861, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA862, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA863, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA864, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA865, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA866, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA867, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA868, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA869, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA86A, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA86B, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA86C, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA86D, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA86E, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA86F, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA870, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA871, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA872, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA873, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA874, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA875, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA876, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA877, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA878, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA879, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA87A, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA87B, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA87C, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA87D, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA87E, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA87F, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA880, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA881, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA882, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA883, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA884, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA885, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA886, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA887, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA888, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA889, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA88A, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA88B, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA88C, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA88D, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA88E, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA88F, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA890, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA891, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA892, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA893, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA894, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA895, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA896, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA897, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA898, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA899, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA89A, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA89B, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA89C, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA89D, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA89E, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA89F, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8A0, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8A1, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8A2, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8A3, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8A4, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8A5, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8A6, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8A7, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8A8, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8A9, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8AA, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8AB, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8AC, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8AD, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8AE, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8AF, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8B0, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8B1, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8B2, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8B3, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8B4, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8B5, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA8B6, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8B7, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8B8, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8B9, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8BA, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8BB, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8BC, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8BD, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8BE, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8BF, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8C0, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8C1, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8C2, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8C3, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8C4, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8C5, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8C6, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8C7, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8C8, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8C9, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8CA, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8CB, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8CC, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8CD, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8CE, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8CF, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8D0, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8D1, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8D2, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8D3, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8D4, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8D5, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8D6, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8D7, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8D8, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8D9, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8DA, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8DB, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8DC, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8DD, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8DE, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8DF, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8E0, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8E1, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8E2, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8E3, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8E4, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8E5, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8E6, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8E7, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8E8, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8E9, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8EA, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8EB, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8EC, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8ED, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8EE, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8EF, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8F0, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8F1, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8F2, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8F3, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8F4, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8F5, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8F6, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8F7, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA8F8, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8F9, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8FA, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8FB, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8FC, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8FD, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA8FE, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA8FF, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA900, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xA901, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA902, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA903, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA904, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA905, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA906, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA907, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA908, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA909, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA90A, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA90B, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA90C, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA90D, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA90E, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA90F, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA910, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA911, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA912, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA913, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA914, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA915, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA916, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA917, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA918, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA919, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA91A, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA91B, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA91C, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA91D, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA91E, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA91F, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA920, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA921, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA922, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA923, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA924, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA925, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA926, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA927, TrapAdapterId::Window.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA928, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA929, TrapAdapterId::Window.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA92A, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA92B, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA92C, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA92D, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA92E, TrapAdapterId::Window.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA92F, TrapAdapterId::Window.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA930, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA931, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA932, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA933, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA934, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA935, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA936, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA937, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA938, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA939, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA93A, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA93B, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA93C, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA93D, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA93E, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA93F, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA940, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA941, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA942, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA943, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA944, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA945, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA946, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA947, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA948, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA949, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA94A, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA94B, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA94C, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA94D, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA94E, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA94F, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA950, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA951, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA952, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA953, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA954, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA955, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA956, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA957, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA958, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA959, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA95A, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA95B, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA95C, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA95D, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA95E, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA95F, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA960, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA961, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA962, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA963, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA964, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA965, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA966, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA967, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA968, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA969, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA96A, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA96B, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA96C, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA96D, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA96E, TrapAdapterId::Event.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA96F, TrapAdapterId::Event.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA970, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA971, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA972, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA973, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA974, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA975, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA976, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA977, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA978, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA979, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA97A, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA97B, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA97C, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA97D, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA97E, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA97F, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA980, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA981, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA982, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA983, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA984, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA985, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA986, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA987, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA988, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA989, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA98A, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA98B, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA98C, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA98D, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA98E, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA98F, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA990, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA991, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA992, TrapAdapterId::Resource.mask()),
    DefaultTrapRoute::new(0xA993, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA994, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA995, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA996, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA997, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA998, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA999, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA99A, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA99B, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA99C, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA99D, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA99E, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA99F, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9A0, TrapAdapterId::Resource.mask()),
    DefaultTrapRoute::new(0xA9A1, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9A2, TrapAdapterId::Resource.mask()),
    DefaultTrapRoute::new(0xA9A3, TrapAdapterId::Resource.mask()),
    DefaultTrapRoute::new(0xA9A4, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9A5, TrapAdapterId::Resource.mask()),
    DefaultTrapRoute::new(0xA9A6, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9A7, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9A8, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9A9, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9AA, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9AB, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9AC, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9AD, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9AE, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9AF, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9B0, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9B1, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9B2, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9B3, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9B4, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9B5, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9B6, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9B7, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9B8, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9B9, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9BA, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9BB, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9BC, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9BD, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xA9BE, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9BF, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9C0, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9C1, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9C2, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9C3, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9C4, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9C5, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9C6, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9C7, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9C8, TrapAdapterId::Sound.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9C9, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9CA, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9CB, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9CC, TrapAdapterId::Dialog.mask()),
    DefaultTrapRoute::new(0xA9CD, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9CE, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9CF, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9D0, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9D1, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9D2, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9D3, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9D4, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9D5, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9D6, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9D7, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9D8, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9D9, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9DA, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9DB, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9DC, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9DD, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9DE, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9DF, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9E0, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9E1, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA9E2, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA9E3, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA9E4, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA9E5, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9E6, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9E7, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9E8, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9E9, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9EA, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9EB, TrapAdapterId::Sane.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9EC, TrapAdapterId::Sane.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9ED, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9EE, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9EF, TrapAdapterId::Memory.mask()),
    DefaultTrapRoute::new(0xA9F0, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xA9F1, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9F2, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9F3, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9F4, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9F5, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9F6, TrapAdapterId::Resource.mask()),
    DefaultTrapRoute::new(0xA9F7, TrapAdapterId::Resource.mask()),
    DefaultTrapRoute::new(0xA9F8, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9F9, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9FA, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9FB, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9FC, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9FD, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9FE, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xA9FF, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xAA00, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA01, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA02, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA03, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA04, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA05, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA06, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA07, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA08, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA09, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA0A, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA0B, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA0C, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA0D, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA0E, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA0F, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA10, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA11, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA12, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA13, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA14, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA15, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA16, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA17, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA18, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA19, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA1A, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA1B, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA1C, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA1D, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA1E, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA1F, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA20, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA21, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA22, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA23, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA24, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA25, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA26, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA27, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA28, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA29, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA2A, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA2B, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA2C, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA2D, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA2E, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA2F, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA30, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA31, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA32, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA33, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA34, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA35, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA36, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA37, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA38, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA39, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA3A, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA3B, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA3C, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA3D, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA3E, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA3F, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA40, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA41, TrapAdapterId::Window.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA42, TrapAdapterId::Window.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA43, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA44, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA45, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xAA46, TrapAdapterId::Window.mask()),
    DefaultTrapRoute::new(0xAA47, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA48, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA49, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA4A, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA4B, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA4C, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA4D, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA4E, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA4F, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA50, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA51, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA52, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA53, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xAA54, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xAA55, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA56, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA57, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xAA58, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA59, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xAA5A, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xAA5B, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA5C, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA5D, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA5E, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA5F, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA60, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA61, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA62, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA63, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA64, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA65, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA66, TrapAdapterId::Menu.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA67, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA68, TrapAdapterId::Dialog.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA69, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA6A, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA6B, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA6C, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA6D, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA6E, TrapAdapterId::Unimplemented.mask()),
    DefaultTrapRoute::new(0xAA6F, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA70, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA71, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA72, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA73, TrapAdapterId::Control.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA74, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA75, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA76, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA77, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA78, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA79, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA7A, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA7B, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA7C, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA7D, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA7E, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA7F, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA80, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA81, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA82, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA83, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA84, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA85, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA86, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA87, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA88, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA89, TrapAdapterId::Resource.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA8A, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA8B, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA8C, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA8D, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA8E, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA8F, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA90, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA91, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA92, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA93, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA94, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA95, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA96, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA97, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA98, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA99, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAA9A, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA9B, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA9C, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA9D, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA9E, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAA9F, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAAA0, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAAA1, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAA2, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAAA3, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAA4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAA5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAA6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAA7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAA8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAA9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAAA, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAAB, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAAC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAAD, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAAE, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAAF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAB0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAB1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAB2, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAB3, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAB4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAB5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAB6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAB7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAB8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAB9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAABA, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAABB, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAABC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAABD, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAABE, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAABF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAC0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAC1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAC2, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAC3, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAC4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAC5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAC6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAC7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAC8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAC9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAACA, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAACB, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAACC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAACD, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAACE, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAACF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAD0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAD1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAD2, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAD3, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAD4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAD5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAD6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAD7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAD8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAD9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAADA, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAADB, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAADC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAADD, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAADE, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAADF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAE0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAE1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAE2, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAE3, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAE4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAE5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAE6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAE7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAE8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAE9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAEA, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAEB, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAEC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAED, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAEE, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAEF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAF0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAF1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAF2, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAF3, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAF4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAF5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAF6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAF7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAF8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAF9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAFA, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAFB, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAFC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAFD, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAAFE, TrapAdapterId::Toolbox.mask()),
    DefaultTrapRoute::new(0xAAFF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB00, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB01, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB02, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB03, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB04, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAB05, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAB06, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB07, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB08, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAB09, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB0A, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB0B, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB0C, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB0D, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB0E, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB0F, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB10, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB11, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB12, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB13, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB14, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB15, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB16, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB17, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB18, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB19, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB1A, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB1B, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB1C, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAB1D, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAB1E, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAB1F, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xAB20, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB21, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB22, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB23, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB24, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB25, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB26, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB27, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB28, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB29, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB2A, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB2B, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB2C, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB2D, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB2E, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB2F, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB30, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB31, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB32, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB33, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB34, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB35, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB36, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB37, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB38, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB39, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB3A, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB3B, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB3C, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB3D, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB3E, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB3F, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB40, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB41, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB42, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB43, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB44, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB45, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB46, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB47, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB48, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB49, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB4A, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB4B, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB4C, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB4D, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB4E, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB4F, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB50, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB51, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB52, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB53, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB54, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB55, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB56, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB57, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB58, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB59, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB5A, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB5B, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB5C, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB5D, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB5E, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB5F, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB60, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB61, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB62, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB63, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB64, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB65, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB66, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB67, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB68, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB69, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB6A, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB6B, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB6C, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB6D, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB6E, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB6F, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB70, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB71, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB72, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB73, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB74, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB75, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB76, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB77, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB78, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB79, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB7A, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB7B, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB7C, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB7D, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB7E, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB7F, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB80, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB81, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB82, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB83, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB84, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB85, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB86, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB87, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB88, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB89, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB8A, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB8B, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB8C, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB8D, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB8E, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB8F, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB90, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB91, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB92, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB93, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB94, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB95, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB96, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB97, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB98, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB99, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB9A, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB9B, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB9C, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB9D, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB9E, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xAB9F, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABA0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABA1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABA2, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABA3, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABA4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABA5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABA6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABA7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABA8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABA9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABAA, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABAB, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABAC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABAD, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABAE, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABAF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABB0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABB1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABB2, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABB3, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABB4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABB5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABB6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABB7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABB8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABB9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABBA, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABBB, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABBC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABBD, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABBE, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABBF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABC0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABC1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABC2, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABC3, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xABC4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABC5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABC6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABC7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABC8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABC9, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABCA, TrapAdapterId::QuickDraw.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABCB, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABCC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABCD, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABCE, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABCF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABD0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABD1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABD2, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABD3, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABD4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABD5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABD6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABD7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABD8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABD9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABDA, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABDB, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABDC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABDD, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABDE, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABDF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABE0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABE1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABE2, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABE3, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABE4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABE5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABE6, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABE7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABE8, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABE9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABEA, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABEB, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xABEC, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABED, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABEE, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABEF, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABF0, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABF1, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABF2, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABF3, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABF4, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABF5, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABF6, TrapAdapterId::Collection.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABF7, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABF8, TrapAdapterId::QuickDraw.mask()),
    DefaultTrapRoute::new(0xABF9, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABFA, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABFB, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABFC, TrapAdapterId::Toolbox.mask() | TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABFD, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABFE, TrapAdapterId::Nonterminal.mask()),
    DefaultTrapRoute::new(0xABFF, TrapAdapterId::Memory.mask()),
]
